/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\light_without_stand.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/light_without_stand/light_without_stand.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_bulb.geometry} material={materials['Light bulb']} rotation={[-Math.PI / 2, 0, -1.57]} scale={2.39} />
      <mesh geometry={nodes['Construction_-_piece'].geometry} material={materials.Construction} position={[0.01, 0, 0]} rotation={[-Math.PI / 2, 0, -1.57]} scale={2.39} />
      <mesh geometry={nodes.Holder.geometry} material={materials.Holder} rotation={[-Math.PI / 2, 0, -1.57]} scale={2.39} />
    </group>
  )
}

useGLTF.preload('/light_without_stand.gltf')
